In [1]:
import numpy as np


In [2]:
!pip install numpy

In [3]:
arr = np.array([1,2,3,4,5])

In [25]:
arr2 = np.array([[1, 2, 3], [4, 5, 6]])  # 2D array
print(arr2)  

[[1 2 3]
 [4 5 6]]


In [5]:
np.zeros((3,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [6]:
np.ones((3,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [7]:
np.full((4,4),8)

array([[8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8],
       [8, 8, 8, 8]])

In [8]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [9]:
np.arange(1,100,5)

array([ 1,  6, 11, 16, 21, 26, 31, 36, 41, 46, 51, 56, 61, 66, 71, 76, 81,
       86, 91, 96])

In [10]:
np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [11]:
arr = np.array([[10, 20, 30], [40, 50, 60]])

In [12]:
arr

array([[10, 20, 30],
       [40, 50, 60]])

In [13]:
arr.shape


(2, 3)

In [14]:
arr.size

6

In [15]:
arr.ndim

2

In [16]:
arr.dtype

dtype('int64')

In [22]:
arr = np.array([1, 2, 3], dtype=np.float32)  # Explicit type
print(arr.dtype)  # float32

float32


In [23]:
arr_int = arr.astype(np.int32)  # Convert float to int
print(arr_int)  # [1 2 3]

[1 2 3]
