In [4]:
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [5]:
arr


array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [6]:
flat = arr.flatten()

In [7]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [8]:
flat[0]

np.int64(1)

In [9]:
flat[:5]

array([1, 2, 3, 4, 5])

In [10]:
flat[2:]

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [11]:
flat

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [12]:
b = flat[0:5]

In [13]:
b

array([1, 2, 3, 4, 5])

In [14]:
b[0]= 12345

In [15]:
b

array([12345,     2,     3,     4,     5])

In [16]:
flat

array([12345,     2,     3,     4,     5,     6,     7,     8,     9,
          10,    11,    12])

In [35]:
arr = np.array([10, 20, 30, 40, 50])
idx = [0, 2, 4]  # Indices to select
print(arr[idx])  # [10 30 50]

[10 30 50]


In [36]:
arr[arr>10]

array([20, 30, 40, 50])

In [40]:
#Create a 3×3 array filled with random numbers and print its shape.
import numpy as np
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [41]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [42]:
arr.shape

(3, 3)

In [49]:
#Convert an array of floats [1.1, 2.2, 3.3] into integers.
import numpy as np
float_array = np.array([1.1, 2.2, 3.3])
int_array = float_array.astype(int)
print(int_array)  # Output: [1 2 3]


[1 2 3]


In [50]:
#Use fancy indexing to extract even numbers from [1, 2, 3, 4, 5, 6]
arr= np.array([1, 2, 3, 4, 5, 6])

In [51]:
arr

array([1, 2, 3, 4, 5, 6])

In [56]:
even_numbers = arr[arr % 2 == 0]

print(even_numbers)  # Output: [2 4 6]


[2 4 6]


In [57]:
#Reshape a 1D array of size 9 into a 3×3 matrix.
arr=np.array([1,2,3,4,5,6,7,8,9])

In [58]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
reshaped=arr.reshape(3,3)

In [60]:
reshaped

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
#Use boolean masking to filter numbers greater than 50 in an array.
arr = np.array([10,20,50,60,70])

In [62]:
arr[arr>50]

array([60, 70])