In [7]:
import numpy as  np
import time
# Python lis t
size = 1_000_000
list1 = list(range(size))
list2 = list(range(size))
 
start = time.time()
result = [x + y for x, y in zip(list1, list2)]
end = time.time()
print("Python list addition time:", end - start) 

Python list addition time: 0.1720566749572754


In [8]:
l1 = [1,2,3,4]
l2= [2,4,5,6]

In [9]:
list(zip(l1,l2))

[(1, 2), (2, 4), (3, 5), (4, 6)]

In [10]:
# NumPy array
arr1 = np.array(list1)
arr2 = np.array(list2)
 
start = time.time()
result = arr1 + arr2  # Vectorized operation
end = time.time()
print("NumPy array addition time:", end - start)

NumPy array addition time: 0.04727768898010254


In [11]:
 
# Creating a 1D NumPy array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)
 

[1 2 3 4 5]


In [12]:
# Creating a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [13]:
# Checking type and shape
print("Type:", type(arr1))
print("Shape:", arr2.shape)

Type: <class 'numpy.ndarray'>
Shape: (2, 3)


In [14]:
import sys
 
list_data = list(range(1000))
numpy_data = np.array(list_data)
 
print("Python list size:", sys.getsizeof(list_data) * len(list_data), "bytes")
print("NumPy array size:", numpy_data.nbytes, "bytes")

Python list size: 8056000 bytes
NumPy array size: 8000 bytes


In [17]:
# Python list (loop-based)
list_squares = [x ** 2 for x in list1]

# NumPy (vectorized)
numpy_squares = arr1 ** 2

In [18]:
import time
import numpy as np

# Example input data
list1 = list(range(1000000))
arr1 = np.array(list1)

# Time Python list operation
start = time.time()
list_squares = [x ** 2 for x in list1]
end = time.time()
print("List comprehension time:", end - start)

# Time NumPy vectorized operation
start = time.time()
numpy_squares = arr1 ** 2
end = time.time()
print("NumPy vectorized time:", end - start)


List comprehension time: 0.08536791801452637
NumPy vectorized time: 0.0030863285064697266
